using System.Globalization;

namespace IndepenDesk;

/// <summary>
/// Basit yerelleştirme: sistem dilini otomatik algılar (tray menüsünden değiştirilebilir,
/// tercih settings.json'da saklanır). Desteklenen diller: en, tr, de, fr, it, ru, zh, ja.
/// </summary>
internal static class L
{
    public static readonly (string Code, string Native)[] Supported =
    {
        ("en", "English"), ("tr", "Türkçe"), ("de", "Deutsch"), ("fr", "Français"),
        ("it", "Italiano"), ("ru", "Русский"), ("zh", "中文"), ("ja", "日本語")
    };

    /// <summary>"auto" veya dil kodu.</summary>
    public static string Override { get; private set; } = "auto";
    private static Dictionary<string, string> _t = null!;

    static L()
    {
        Override = SettingsStore.GetString("language") ?? "auto";
        Apply();
    }

    public static void SetOverride(string codeOrAuto)
    {
        Override = codeOrAuto;
        SettingsStore.SetString("language", Override);
        Apply();
    }

    private static void Apply()
    {
        string code = Override == "auto"
            ? CultureInfo.CurrentUICulture.TwoLetterISOLanguageName
            : Override;
        _t = Tables.TryGetValue(code, out var t) ? t : Tables["en"];
    }

    public static string T(string key) =>
        _t.TryGetValue(key, out var v) ? v : Tables["en"].TryGetValue(key, out var e) ? e : key;

    public static string F(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, T(key), args);

    private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        ["en"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — independent desktops per monitor",
            ["menu.overview"] = "Overview  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Restore all windows",
            ["menu.sharedTaskbar"] = "Shared taskbar (click an icon to jump to its desktop)",
            ["menu.warnUnmanageable"] = "Warn when a window cannot be hidden",
            ["menu.help"] = "How to use…",
            ["menu.language"] = "Language",
            ["menu.lang.auto"] = "System (auto)",
            ["menu.startup"] = "Start with Windows",
            ["menu.update"] = "Check for updates…",
            ["menu.exit"] = "Exit",
            ["msg.hotkeyFail"] = "Some shortcuts could not be registered (another app may be using them): ",
            ["msg.alreadyRunning"] = "IndepenDesk is already running.",
            ["msg.startupFail"] = "The startup setting could not be changed. See the diagnostic log for details.",
            ["msg.windowControlFail"] = "A window could not be hidden safely (often an administrator window), so the requested desktop operation was cancelled.",
            ["msg.sharedTaskbarFail"] = "The shared taskbar mode could not be switched (often an administrator window); the previous mode was kept.",
            ["msg.windowSkipped"] = "\"{0}\" ({1}) could not be hidden — likely an administrator window. It was skipped and stays visible.",
            ["update.title"] = "IndepenDesk update",
            ["update.available"] = "New version {0} is available (you have {1}).\nOpen the download page?",
            ["update.none"] = "You are running the latest version ({0}).",
            ["update.error"] = "Could not contact GitHub to check for updates. Please try again later.",
            ["update.rateLimited"] = "GitHub is temporarily limiting update checks. Please try again later.",
            ["update.invalidVersion"] = "The release version could not be read. Please open the prcyangli Releases page manually.",
            ["osd.desktop"] = "Desktop {0}",
            ["ov.title"] = "IndepenDesk — Overview",
            ["ov.legend"] = "⠿  drag a window box onto any desktop card   •   drag a card title onto another monitor row   •   right-click a window: move menu   •   click a card: switch   •   Esc: close",
            ["ov.monitor"] = "Monitor {0}",
            ["ov.desktop"] = "⠿ Desktop {0}",
            ["ov.active"] = "ACTIVE",
            ["ov.empty"] = "Empty — drag windows here",
            ["ov.drop"] = "⬇  Drop here",
            ["ov.menu.move"] = "Move to:  Monitor {0}  •  Desktop {1}",
            ["ov.menu.activeSuffix"] = "  (active)",
            ["ov.menu.goto"] = "Go to this window",
            ["ov.tip.window"] = "Drag onto a desktop card  •  Right-click: move menu",
            ["ov.tip.header"] = "Drag onto another monitor row to move the whole desktop",
            ["ov.tip.add"] = "Create a new desktop on this monitor without switching",
            ["ov.tip.closeDesktop"] = "Close this desktop",
            ["help.title"] = "How to use IndepenDesk",
            ["help.shortcuts.header"] = "Keyboard shortcuts",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   previous / next desktop on the monitor under the mouse (at the end, → creates a new one)\nCtrl+Alt+↑   —   overview: drag && drop windows and desktops\nCtrl+Alt+1..9   —   jump to the desktop with that global number\nCtrl+Alt+Shift+← / →   —   move the active window to the adjacent desktop and follow it",
            ["help.touchpad.header"] = "Touchpad setup (overrides the Windows default)",
            ["help.touchpad.body"] = "1.  Open Settings → Bluetooth && devices → Touchpad → Advanced gestures.\n2.  Under the four-finger gestures pick \"Custom shortcut\" for each direction and record:\n      swipe left → Ctrl+Alt+←        swipe right → Ctrl+Alt+→        swipe up → Ctrl+Alt+↑\n3.  Recording a custom shortcut automatically replaces the Windows default\n      (the global desktop switch), so only the monitor under your cursor will switch.\n4.  While an elevated (administrator) window is focused, touchpad custom shortcuts are dropped\n      by Windows security (UIPI); switch with the physical keyboard or the tray menu instead.",
            ["help.touchpad.open"] = "Open touchpad settings",
            ["help.demo.header"] = "Gestures",
            ["help.demo.swipeLR"] = "4-finger swipe left / right  →  switch desktop on the monitor under the cursor",
            ["help.demo.swipeUp"] = "4-finger swipe up  →  overview",
            ["help.close"] = "Close",
        },
        ["tr"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — monitör başına bağımsız masaüstleri",
            ["menu.overview"] = "Genel bakış  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Tüm pencereleri geri getir",
            ["menu.sharedTaskbar"] = "Paylaşılan görev çubuğu (simgeye tıkla, masaüstüne geç)",
            ["menu.warnUnmanageable"] = "Gizlenemeyen pencere olunca uyar",
            ["menu.help"] = "Nasıl kullanılır…",
            ["menu.language"] = "Dil",
            ["menu.lang.auto"] = "Sistem (otomatik)",
            ["menu.startup"] = "Windows ile başlat",
            ["menu.update"] = "Güncellemeleri denetle…",
            ["menu.exit"] = "Çıkış",
            ["msg.hotkeyFail"] = "Bazı kısayollar kaydedilemedi (başka bir uygulama kullanıyor olabilir): ",
            ["msg.alreadyRunning"] = "IndepenDesk zaten çalışıyor.",
            ["msg.startupFail"] = "Başlangıç ayarı değiştirilemedi. Ayrıntılar için tanılama günlüğüne bakın.",
            ["msg.windowControlFail"] = "Bir pencere güvenle gizlenemedi (çoğunlukla yönetici penceresi); istenen masaüstü işlemi iptal edildi.",
            ["msg.sharedTaskbarFail"] = "Paylaşılan görev çubuğu moduna geçilemedi (çoğunlukla yönetici penceresi); önceki mod korundu.",
            ["msg.windowSkipped"] = "\"{0}\" ({1}) gizlenemedi — büyük olasılıkla yönetici penceresi. Atlandı ve görünür kalır.",
            ["update.title"] = "IndepenDesk güncelleme",
            ["update.available"] = "Yeni sürüm {0} yayınlandı (sizdeki: {1}).\nİndirme sayfası açılsın mı?",
            ["update.none"] = "En güncel sürümü kullanıyorsunuz ({0}).",
            ["update.error"] = "Güncellemeleri denetlemek için GitHub'a ulaşılamadı. Lütfen daha sonra tekrar deneyin.",
            ["update.rateLimited"] = "GitHub güncelleme denetimlerini geçici olarak sınırlıyor. Lütfen daha sonra tekrar deneyin.",
            ["update.invalidVersion"] = "Sürüm numarası okunamadı. Lütfen prcyangli Releases sayfasını elle açın.",
            ["osd.desktop"] = "Masaüstü {0}",
            ["ov.title"] = "IndepenDesk — Genel Bakış",
            ["ov.legend"] = "⠿  pencere kutucuğunu istediğiniz masaüstü kartına sürükleyin   •   kart başlığını başka monitör satırına sürükleyin   •   pencereye sağ tık: taşıma menüsü   •   karta tıkla: geç   •   Esc: kapat",
            ["ov.monitor"] = "Monitör {0}",
            ["ov.desktop"] = "⠿ Masaüstü {0}",
            ["ov.active"] = "AKTİF",
            ["ov.empty"] = "Boş — pencereleri buraya sürükleyin",
            ["ov.drop"] = "⬇  Buraya bırak",
            ["ov.menu.move"] = "Taşı:  Monitör {0}  •  Masaüstü {1}",
            ["ov.menu.activeSuffix"] = "  (aktif)",
            ["ov.menu.goto"] = "Bu pencereye git",
            ["ov.tip.window"] = "Bir masaüstü kartına sürükleyin  •  Sağ tık: taşıma menüsü",
            ["ov.tip.header"] = "Başka monitörün satırına sürükleyin: masaüstü komple taşınır",
            ["ov.tip.add"] = "Bu monitörde yeni masaüstü oluştur; geçiş yapma",
            ["ov.tip.closeDesktop"] = "Bu masaüstünü kapat",
            ["help.title"] = "IndepenDesk nasıl kullanılır",
            ["help.shortcuts.header"] = "Klavye kısayolları",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   farenin olduğu monitörde önceki / sonraki masaüstü (sonda → yenisini oluşturur)\nCtrl+Alt+↑   —   genel bakış: pencereleri ve masaüstlerini sürükle-bırak\nCtrl+Alt+1..9   —   global numaralı masaüstüne git\nCtrl+Alt+Shift+← / →   —   aktif pencereyi bitişik masaüstüne taşı ve oraya geç",
            ["help.touchpad.header"] = "Touchpad kurulumu (Windows varsayılanını ezer)",
            ["help.touchpad.body"] = "1.  Ayarlar → Bluetooth ve cihazlar → Dokunmatik yüzey → Gelişmiş hareketler'i açın.\n2.  Dört parmak hareketlerinde her yön için \"Özel kısayol\" seçip şunları kaydedin:\n      sola çekme → Ctrl+Alt+←        sağa çekme → Ctrl+Alt+→        yukarı çekme → Ctrl+Alt+↑\n3.  Özel kısayol kaydettiğiniz anda Windows varsayılanı (tüm ekranları birden kaydıran\n      global geçiş) otomatik olarak devre dışı kalır; yalnızca imlecin olduğu monitör değişir.\n4.  Yükseltilmiş (yönetici) bir pencere odaktayken dokunmatik yüzey özel kısayolları Windows\n      güvenliği (UIPI) tarafından yok sayılır; fiziksel klavyeyi veya tepsi menüsünü kullanın.",
            ["help.touchpad.open"] = "Dokunmatik yüzey ayarlarını aç",
            ["help.demo.header"] = "Hareketler",
            ["help.demo.swipeLR"] = "4 parmak sola / sağa kaydırma  →  imlecin olduğu monitörde masaüstü değiştir",
            ["help.demo.swipeUp"] = "4 parmak yukarı kaydırma  →  genel bakış",
            ["help.close"] = "Kapat",
        },
        ["de"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — unabhängige Desktops pro Monitor",
            ["menu.overview"] = "Übersicht  (Strg+Alt+↑)",
            ["menu.restore"] = "Alle Fenster wiederherstellen",
            ["menu.sharedTaskbar"] = "Gemeinsame Taskleiste (Klick auf Symbol wechselt zum Desktop)",
            ["menu.warnUnmanageable"] = "Warnen, wenn ein Fenster nicht ausgeblendet werden kann",
            ["menu.help"] = "Bedienungsanleitung…",
            ["menu.language"] = "Sprache",
            ["menu.lang.auto"] = "System (automatisch)",
            ["menu.startup"] = "Mit Windows starten",
            ["menu.update"] = "Nach Updates suchen…",
            ["menu.exit"] = "Beenden",
            ["msg.hotkeyFail"] = "Einige Tastenkürzel konnten nicht registriert werden (evtl. von einer anderen App belegt): ",
            ["msg.alreadyRunning"] = "IndepenDesk wird bereits ausgeführt.",
            ["msg.startupFail"] = "Die Autostart-Einstellung konnte nicht geändert werden. Details stehen im Diagnoseprotokoll.",
            ["msg.windowControlFail"] = "Ein Fenster konnte nicht sicher ausgeblendet werden (oft ein Administratorfenster); der angeforderte Desktopvorgang wurde abgebrochen.",
            ["msg.sharedTaskbarFail"] = "Der gemeinsame Taskleisten-Modus konnte nicht gewechselt werden (oft ein Administratorfenster); der vorherige Modus wurde beibehalten.",
            ["msg.windowSkipped"] = "\"{0}\" ({1}) konnte nicht ausgeblendet werden — vermutlich ein Administratorfenster. Es wird übersprungen und bleibt sichtbar.",
            ["update.title"] = "IndepenDesk-Update",
            ["update.available"] = "Neue Version {0} ist verfügbar (installiert: {1}).\nDownload-Seite öffnen?",
            ["update.none"] = "Sie verwenden bereits die neueste Version ({0}).",
            ["update.error"] = "GitHub konnte für die Update-Prüfung nicht erreicht werden. Bitte versuchen Sie es später erneut.",
            ["update.rateLimited"] = "GitHub begrenzt Update-Prüfungen vorübergehend. Bitte versuchen Sie es später erneut.",
            ["update.invalidVersion"] = "Die Release-Version konnte nicht gelesen werden. Öffnen Sie die prcyangli-Releases bitte manuell.",
            ["osd.desktop"] = "Desktop {0}",
            ["ov.title"] = "IndepenDesk — Übersicht",
            ["ov.legend"] = "⠿  Fensterkästchen auf eine Desktop-Karte ziehen   •   Kartentitel auf eine andere Monitorzeile ziehen   •   Rechtsklick auf Fenster: Verschieben-Menü   •   Karte anklicken: wechseln   •   Esc: schließen",
            ["ov.monitor"] = "Monitor {0}",
            ["ov.desktop"] = "⠿ Desktop {0}",
            ["ov.active"] = "AKTIV",
            ["ov.empty"] = "Leer — Fenster hierher ziehen",
            ["ov.drop"] = "⬇  Hier ablegen",
            ["ov.menu.move"] = "Verschieben:  Monitor {0}  •  Desktop {1}",
            ["ov.menu.activeSuffix"] = "  (aktiv)",
            ["ov.menu.goto"] = "Zu diesem Fenster wechseln",
            ["ov.tip.window"] = "Auf eine Desktop-Karte ziehen  •  Rechtsklick: Verschieben-Menü",
            ["ov.tip.header"] = "Auf eine andere Monitorzeile ziehen, um den ganzen Desktop zu verschieben",
            ["ov.tip.add"] = "Neuen Desktop auf diesem Monitor erstellen, ohne zu wechseln",
            ["ov.tip.closeDesktop"] = "Diesen Desktop schließen",
            ["help.title"] = "IndepenDesk-Bedienungsanleitung",
            ["help.shortcuts.header"] = "Tastenkürzel",
            ["help.shortcuts.body"] = "Strg+Alt+← / →   —   vorheriger / nächster Desktop auf dem Monitor unter der Maus (am Ende erstellt → einen neuen)\nStrg+Alt+↑   —   Übersicht: Fenster und Desktops per Drag && Drop verschieben\nStrg+Alt+1..9   —   zum Desktop mit dieser globalen Nummer springen\nStrg+Alt+Umschalt+← / →   —   aktives Fenster auf den Nachbar-Desktop verschieben",
            ["help.touchpad.header"] = "Touchpad einrichten (überschreibt den Windows-Standard)",
            ["help.touchpad.body"] = "1.  Einstellungen → Bluetooth && Geräte → Touchpad → Erweiterte Gesten öffnen.\n2.  Bei den Vier-Finger-Gesten für jede Richtung \"Benutzerdefinierte Tastenkombination\" wählen:\n      nach links → Strg+Alt+←        nach rechts → Strg+Alt+→        nach oben → Strg+Alt+↑\n3.  Eine benutzerdefinierte Tastenkombination ersetzt automatisch den Windows-Standard\n      (globaler Desktopwechsel); es wechselt nur der Monitor unter dem Cursor.\n4.  Solange ein Fenster mit Administratorrechten fokussiert ist, verwirft die Windows-Sicherheit\n      (UIPI) eigene Touchpad-Kürzel; nutzen Sie dann die physische Tastatur oder das Tray-Menü.",
            ["help.touchpad.open"] = "Touchpad-Einstellungen öffnen",
            ["help.demo.header"] = "Gesten",
            ["help.demo.swipeLR"] = "Mit 4 Fingern nach links / rechts wischen  →  Desktop auf dem Monitor unter dem Cursor wechseln",
            ["help.demo.swipeUp"] = "Mit 4 Fingern nach oben wischen  →  Übersicht",
            ["help.close"] = "Schließen",
        },
        ["fr"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — bureaux indépendants par moniteur",
            ["menu.overview"] = "Vue d'ensemble  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Restaurer toutes les fenêtres",
            ["menu.sharedTaskbar"] = "Barre des tâches partagée (cliquer sur une icône pour aller à son bureau)",
            ["menu.warnUnmanageable"] = "Avertir quand une fenêtre ne peut pas être masquée",
            ["menu.help"] = "Mode d'emploi…",
            ["menu.language"] = "Langue",
            ["menu.lang.auto"] = "Système (auto)",
            ["menu.startup"] = "Lancer au démarrage de Windows",
            ["menu.update"] = "Rechercher des mises à jour…",
            ["menu.exit"] = "Quitter",
            ["msg.hotkeyFail"] = "Certains raccourcis n'ont pas pu être enregistrés (peut-être utilisés par une autre application) : ",
            ["msg.alreadyRunning"] = "IndepenDesk est déjà en cours d'exécution.",
            ["msg.startupFail"] = "Le paramètre de démarrage n'a pas pu être modifié. Consultez le journal de diagnostic.",
            ["msg.windowControlFail"] = "Une fenêtre n'a pas pu être masquée en sécurité (souvent avec des droits administrateur) ; l'opération demandée a été annulée.",
            ["msg.sharedTaskbarFail"] = "Impossible d'activer le mode barre des tâches partagée (souvent une fenêtre administrateur) ; le mode précédent a été conservé.",
            ["msg.windowSkipped"] = "« {0} » ({1}) n'a pas pu être masquée — probablement une fenêtre administrateur. Elle a été ignorée et reste visible.",
            ["update.title"] = "Mise à jour d'IndepenDesk",
            ["update.available"] = "La nouvelle version {0} est disponible (vous avez {1}).\nOuvrir la page de téléchargement ?",
            ["update.none"] = "Vous utilisez déjà la dernière version ({0}).",
            ["update.error"] = "Impossible de contacter GitHub pour rechercher les mises à jour. Réessayez plus tard.",
            ["update.rateLimited"] = "GitHub limite temporairement les recherches de mises à jour. Réessayez plus tard.",
            ["update.invalidVersion"] = "La version publiée n'a pas pu être lue. Ouvrez manuellement la page Releases de prcyangli.",
            ["osd.desktop"] = "Bureau {0}",
            ["ov.title"] = "IndepenDesk — Vue d'ensemble",
            ["ov.legend"] = "⠿  faites glisser une fenêtre sur une carte de bureau   •   faites glisser le titre d'une carte sur une autre ligne de moniteur   •   clic droit sur une fenêtre : menu de déplacement   •   clic sur une carte : basculer   •   Échap : fermer",
            ["ov.monitor"] = "Moniteur {0}",
            ["ov.desktop"] = "⠿ Bureau {0}",
            ["ov.active"] = "ACTIF",
            ["ov.empty"] = "Vide — glissez des fenêtres ici",
            ["ov.drop"] = "⬇  Déposer ici",
            ["ov.menu.move"] = "Déplacer vers :  Moniteur {0}  •  Bureau {1}",
            ["ov.menu.activeSuffix"] = "  (actif)",
            ["ov.menu.goto"] = "Aller à cette fenêtre",
            ["ov.tip.window"] = "Glissez sur une carte de bureau  •  Clic droit : menu de déplacement",
            ["ov.tip.header"] = "Glissez sur une autre ligne de moniteur pour déplacer tout le bureau",
            ["ov.tip.add"] = "Créer un nouveau bureau sur ce moniteur sans y basculer",
            ["ov.tip.closeDesktop"] = "Fermer ce bureau",
            ["help.title"] = "Mode d'emploi d'IndepenDesk",
            ["help.shortcuts.header"] = "Raccourcis clavier",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   bureau précédent / suivant sur le moniteur sous la souris (à la fin, → en crée un nouveau)\nCtrl+Alt+↑   —   vue d'ensemble : glisser-déposer fenêtres et bureaux\nCtrl+Alt+1..9   —   aller au bureau portant ce numéro global\nCtrl+Alt+Maj+← / →   —   déplacer la fenêtre active vers le bureau adjacent",
            ["help.touchpad.header"] = "Configuration du pavé tactile (remplace le comportement Windows)",
            ["help.touchpad.body"] = "1.  Ouvrez Paramètres → Bluetooth et appareils → Pavé tactile → Mouvements avancés.\n2.  Pour les mouvements à quatre doigts, choisissez « Raccourci personnalisé » pour chaque direction :\n      vers la gauche → Ctrl+Alt+←        vers la droite → Ctrl+Alt+→        vers le haut → Ctrl+Alt+↑\n3.  Un raccourci personnalisé remplace automatiquement le comportement Windows par défaut\n      (changement global de bureau) ; seul le moniteur sous le curseur bascule.\n4.  Lorsqu'une fenêtre d'administrateur (élevée) est active, la sécurité Windows (UIPI) ignore\n      les raccourcis personnalisés du pavé tactile ; utilisez alors le clavier physique ou le\n      menu de la zone de notification.",
            ["help.touchpad.open"] = "Ouvrir les paramètres du pavé tactile",
            ["help.demo.header"] = "Gestes",
            ["help.demo.swipeLR"] = "Balayage à 4 doigts vers la gauche / droite  →  changer de bureau sur le moniteur sous le curseur",
            ["help.demo.swipeUp"] = "Balayage à 4 doigts vers le haut  →  vue d'ensemble",
            ["help.close"] = "Fermer",
        },
        ["it"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — desktop indipendenti per ogni monitor",
            ["menu.overview"] = "Panoramica  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Ripristina tutte le finestre",
            ["menu.sharedTaskbar"] = "Barra delle applicazioni condivisa (clic su un'icona per passare al desktop)",
            ["menu.warnUnmanageable"] = "Avvisa quando una finestra non può essere nascosta",
            ["menu.help"] = "Come si usa…",
            ["menu.language"] = "Lingua",
            ["menu.lang.auto"] = "Sistema (auto)",
            ["menu.startup"] = "Avvia con Windows",
            ["menu.update"] = "Controlla aggiornamenti…",
            ["menu.exit"] = "Esci",
            ["msg.hotkeyFail"] = "Alcune scorciatoie non sono state registrate (forse usate da un'altra app): ",
            ["msg.alreadyRunning"] = "IndepenDesk è già in esecuzione.",
            ["msg.startupFail"] = "Impossibile modificare l'impostazione di avvio. Consulta il registro diagnostico.",
            ["msg.windowControlFail"] = "Non è stato possibile nascondere una finestra in sicurezza (spesso con privilegi amministrativi); l'operazione richiesta è stata annullata.",
            ["msg.sharedTaskbarFail"] = "Impossibile attivare la modalità barra condivisa (spesso una finestra amministratore); la modalità precedente è stata mantenuta.",
            ["msg.windowSkipped"] = "\"{0}\" ({1}) non può essere nascosta — probabilmente una finestra amministratore. Viene ignorata e resta visibile.",
            ["update.title"] = "Aggiornamento IndepenDesk",
            ["update.available"] = "È disponibile la nuova versione {0} (installata: {1}).\nAprire la pagina di download?",
            ["update.none"] = "Stai già usando l'ultima versione ({0}).",
            ["update.error"] = "Impossibile contattare GitHub per controllare gli aggiornamenti. Riprova più tardi.",
            ["update.rateLimited"] = "GitHub sta limitando temporaneamente i controlli degli aggiornamenti. Riprova più tardi.",
            ["update.invalidVersion"] = "Impossibile leggere la versione pubblicata. Apri manualmente la pagina Releases di prcyangli.",
            ["osd.desktop"] = "Desktop {0}",
            ["ov.title"] = "IndepenDesk — Panoramica",
            ["ov.legend"] = "⠿  trascina una finestra su una scheda desktop   •   trascina il titolo di una scheda su un'altra riga di monitor   •   clic destro su una finestra: menu di spostamento   •   clic su una scheda: passa   •   Esc: chiudi",
            ["ov.monitor"] = "Monitor {0}",
            ["ov.desktop"] = "⠿ Desktop {0}",
            ["ov.active"] = "ATTIVO",
            ["ov.empty"] = "Vuoto — trascina qui le finestre",
            ["ov.drop"] = "⬇  Rilascia qui",
            ["ov.menu.move"] = "Sposta in:  Monitor {0}  •  Desktop {1}",
            ["ov.menu.activeSuffix"] = "  (attivo)",
            ["ov.menu.goto"] = "Vai a questa finestra",
            ["ov.tip.window"] = "Trascina su una scheda desktop  •  Clic destro: menu di spostamento",
            ["ov.tip.header"] = "Trascina su un'altra riga di monitor per spostare l'intero desktop",
            ["ov.tip.add"] = "Crea un nuovo desktop su questo monitor senza passare ad esso",
            ["ov.tip.closeDesktop"] = "Chiudi questo desktop",
            ["help.title"] = "Come si usa IndepenDesk",
            ["help.shortcuts.header"] = "Scorciatoie da tastiera",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   desktop precedente / successivo sul monitor sotto il mouse (alla fine, → ne crea uno nuovo)\nCtrl+Alt+↑   —   panoramica: trascina finestre e desktop\nCtrl+Alt+1..9   —   vai al desktop con quel numero globale\nCtrl+Alt+Maiusc+← / →   —   sposta la finestra attiva sul desktop adiacente",
            ["help.touchpad.header"] = "Configurazione del touchpad (sostituisce il comportamento di Windows)",
            ["help.touchpad.body"] = "1.  Apri Impostazioni → Bluetooth e dispositivi → Touchpad → Movimenti avanzati.\n2.  Nei movimenti a quattro dita scegli \"Collegamento personalizzato\" per ogni direzione:\n      scorri a sinistra → Ctrl+Alt+←        scorri a destra → Ctrl+Alt+→        scorri in alto → Ctrl+Alt+↑\n3.  Un collegamento personalizzato sostituisce automaticamente il comportamento predefinito\n      di Windows (cambio globale); cambia solo il monitor sotto il cursore.\n4.  Quando una finestra con privilegi di amministratore è attiva, la sicurezza di Windows (UIPI)\n      ignora le scorciatoie personalizzate del touchpad; usa la tastiera fisica o il menu\n      dell'area di notifica.",
            ["help.touchpad.open"] = "Apri impostazioni touchpad",
            ["help.demo.header"] = "Gesti",
            ["help.demo.swipeLR"] = "Scorrimento a 4 dita a sinistra / destra  →  cambia desktop sul monitor sotto il cursore",
            ["help.demo.swipeUp"] = "Scorrimento a 4 dita in alto  →  panoramica",
            ["help.close"] = "Chiudi",
        },
        ["ru"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — независимые рабочие столы для каждого монитора",
            ["menu.overview"] = "Обзор  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Восстановить все окна",
            ["menu.sharedTaskbar"] = "Общая панель задач (щёлкните значок, чтобы перейти на рабочий стол)",
            ["menu.warnUnmanageable"] = "Предупреждать, если окно не удаётся скрыть",
            ["menu.help"] = "Как пользоваться…",
            ["menu.language"] = "Язык",
            ["menu.lang.auto"] = "Системный (авто)",
            ["menu.startup"] = "Запускать вместе с Windows",
            ["menu.update"] = "Проверить обновления…",
            ["menu.exit"] = "Выход",
            ["msg.hotkeyFail"] = "Не удалось зарегистрировать некоторые сочетания клавиш (возможно, заняты другим приложением): ",
            ["msg.alreadyRunning"] = "IndepenDesk уже запущен.",
            ["msg.startupFail"] = "Не удалось изменить настройку автозапуска. Подробности см. в журнале диагностики.",
            ["msg.windowControlFail"] = "Не удалось безопасно скрыть окно (часто это окно администратора), поэтому запрошенная операция отменена.",
            ["msg.sharedTaskbarFail"] = "Не удалось переключить режим общей панели задач (часто из-за окна администратора); предыдущий режим сохранён.",
            ["msg.windowSkipped"] = "Не удалось скрыть «{0}» ({1}) — вероятно, окно администратора. Оно пропущено и остаётся видимым.",
            ["update.title"] = "Обновление IndepenDesk",
            ["update.available"] = "Доступна новая версия {0} (у вас {1}).\nОткрыть страницу загрузки?",
            ["update.none"] = "У вас уже последняя версия ({0}).",
            ["update.error"] = "Не удалось связаться с GitHub для проверки обновлений. Повторите попытку позже.",
            ["update.rateLimited"] = "GitHub временно ограничивает проверки обновлений. Повторите попытку позже.",
            ["update.invalidVersion"] = "Не удалось прочитать версию выпуска. Откройте страницу Releases prcyangli вручную.",
            ["osd.desktop"] = "Рабочий стол {0}",
            ["ov.title"] = "IndepenDesk — Обзор",
            ["ov.legend"] = "⠿  перетащите окно на карточку рабочего стола   •   перетащите заголовок карточки на строку другого монитора   •   правый клик по окну: меню перемещения   •   клик по карточке: переключиться   •   Esc: закрыть",
            ["ov.monitor"] = "Монитор {0}",
            ["ov.desktop"] = "⠿ Рабочий стол {0}",
            ["ov.active"] = "АКТИВЕН",
            ["ov.empty"] = "Пусто — перетащите окна сюда",
            ["ov.drop"] = "⬇  Отпустите здесь",
            ["ov.menu.move"] = "Переместить:  Монитор {0}  •  Рабочий стол {1}",
            ["ov.menu.activeSuffix"] = "  (активен)",
            ["ov.menu.goto"] = "Перейти к этому окну",
            ["ov.tip.window"] = "Перетащите на карточку рабочего стола  •  Правый клик: меню перемещения",
            ["ov.tip.header"] = "Перетащите на строку другого монитора, чтобы переместить весь рабочий стол",
            ["ov.tip.add"] = "Создать новый рабочий стол на этом мониторе без переключения",
            ["ov.tip.closeDesktop"] = "Закрыть этот рабочий стол",
            ["help.title"] = "Как пользоваться IndepenDesk",
            ["help.shortcuts.header"] = "Сочетания клавиш",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   предыдущий / следующий рабочий стол на мониторе под курсором (в конце → создаёт новый)\nCtrl+Alt+↑   —   обзор: перетаскивание окон и рабочих столов\nCtrl+Alt+1..9   —   перейти к рабочему столу с этим глобальным номером\nCtrl+Alt+Shift+← / →   —   переместить активное окно на соседний рабочий стол",
            ["help.touchpad.header"] = "Настройка сенсорной панели (заменяет стандартное поведение Windows)",
            ["help.touchpad.body"] = "1.  Откройте Параметры → Bluetooth и устройства → Сенсорная панель → Дополнительные жесты.\n2.  Для жестов четырьмя пальцами выберите «Настраиваемое сочетание клавиш» для каждого направления:\n      влево → Ctrl+Alt+←        вправо → Ctrl+Alt+→        вверх → Ctrl+Alt+↑\n3.  Настраиваемое сочетание автоматически заменяет стандартное поведение Windows\n      (глобальное переключение); переключается только монитор под курсором.\n4.  Пока в фокусе окно с правами администратора, защита Windows (UIPI) отбрасывает\n      пользовательские сочетания на сенсорной панели; используйте физическую клавиатуру\n      или меню в области уведомлений.",
            ["help.touchpad.open"] = "Открыть настройки сенсорной панели",
            ["help.demo.header"] = "Жесты",
            ["help.demo.swipeLR"] = "Смахивание 4 пальцами влево / вправо  →  сменить рабочий стол на мониторе под курсором",
            ["help.demo.swipeUp"] = "Смахивание 4 пальцами вверх  →  обзор",
            ["help.close"] = "Закрыть",
        },
        ["zh"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — 每个显示器独立的虚拟桌面",
            ["menu.overview"] = "总览  (Ctrl+Alt+↑)",
            ["menu.restore"] = "恢复所有窗口",
            ["menu.sharedTaskbar"] = "共用任务栏（点击图标跳转桌面）",
            ["menu.warnUnmanageable"] = "窗口无法隐藏时通知",
            ["menu.help"] = "使用说明…",
            ["menu.language"] = "语言",
            ["menu.lang.auto"] = "系统（自动）",
            ["menu.startup"] = "开机自动启动",
            ["menu.update"] = "检查更新…",
            ["menu.exit"] = "退出",
            ["msg.hotkeyFail"] = "部分快捷键注册失败（可能被其他应用占用）：",
            ["msg.alreadyRunning"] = "IndepenDesk 已经在运行。",
            ["msg.startupFail"] = "无法更改开机启动设置。详情请查看诊断日志。",
            ["msg.windowControlFail"] = "有窗口无法安全隐藏（通常是管理员窗口），本次桌面操作已取消。",
            ["msg.sharedTaskbarFail"] = "无法切换共用任务栏模式（通常是管理员窗口），已保持原模式。",
            ["msg.windowSkipped"] = "“{0}”({1}) 无法隐藏——疑似管理员窗口；已跳过，窗口保持可见。",
            ["update.title"] = "IndepenDesk 更新",
            ["update.available"] = "发现新版本 {0}（当前版本 {1}）。\n是否打开下载页面？",
            ["update.none"] = "您已在使用最新版本（{0}）。",
            ["update.error"] = "无法连接 GitHub 检查更新，请稍后重试。",
            ["update.rateLimited"] = "GitHub 暂时限制了更新检查请求，请稍后重试。",
            ["update.invalidVersion"] = "无法解析发布版本，请手动打开 prcyangli 仓库的 Releases 页面。",
            ["osd.desktop"] = "桌面 {0}",
            ["ov.title"] = "IndepenDesk — 总览",
            ["ov.legend"] = "⠿  将窗口拖到桌面卡片或＋   •   拖动卡片标题可重排或跨显示器移动   •   右键窗口：移动菜单   •   点击卡片：切换并保持总览   •   Esc/右上角：关闭",
            ["ov.monitor"] = "显示器 {0}",
            ["ov.desktop"] = "⠿ 桌面 {0}",
            ["ov.active"] = "当前",
            ["ov.empty"] = "空 — 将窗口拖到这里",
            ["ov.drop"] = "⬇  放到这里",
            ["ov.menu.move"] = "移动到：显示器 {0}  •  桌面 {1}",
            ["ov.menu.activeSuffix"] = "（当前）",
            ["ov.menu.goto"] = "转到此窗口",
            ["ov.tip.window"] = "拖到桌面卡片上  •  右键：移动菜单",
            ["ov.tip.header"] = "拖到卡片左/右侧可调整位置；拖到显示器行或＋可移到末尾",
            ["ov.tip.add"] = "点击：新建但不切换；拖入窗口：新建并移动；拖入桌面：移到末尾",
            ["ov.tip.closeDesktop"] = "关闭此桌面",
            ["help.title"] = "IndepenDesk 使用说明",
            ["help.shortcuts.header"] = "键盘快捷键",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   切换鼠标所在显示器的上一个 / 下一个桌面（在末尾按 → 新建桌面）\nCtrl+Alt+↑   —   总览：拖放窗口和桌面\nCtrl+Alt+1..9   —   跳转到对应全局编号的桌面\nCtrl+Alt+Shift+← / →   —   将当前窗口移到相邻桌面并跟随",
            ["help.touchpad.header"] = "触摸板设置（覆盖 Windows 默认行为）",
            ["help.touchpad.body"] = "1.  打开 设置 → 蓝牙和其他设备 → 触摸板 → 高级手势。\n2.  在四指手势中为每个方向选择\"自定义快捷方式\"并录制：\n      向左滑动 → Ctrl+Alt+←        向右滑动 → Ctrl+Alt+→        向上滑动 → Ctrl+Alt+↑\n3.  录制自定义快捷方式后会自动替换 Windows 默认行为（全局桌面切换），\n      只有光标所在的显示器会切换。\n4.  当焦点位于管理员（提权）窗口上时，触摸板的自定义快捷方式会被 Windows 安全机制（UIPI）\n      丢弃（它们属于合成按键）；此时请用实体键盘快捷键或托盘菜单切换。",
            ["help.touchpad.open"] = "打开触摸板设置",
            ["help.demo.header"] = "手势",
            ["help.demo.swipeLR"] = "四指左右滑动  →  切换光标所在显示器的桌面",
            ["help.demo.swipeUp"] = "四指上滑  →  总览",
            ["help.close"] = "关闭",
        },
        ["ja"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — モニターごとに独立したデスクトップ",
            ["menu.overview"] = "オーバービュー  (Ctrl+Alt+↑)",
            ["menu.restore"] = "すべてのウィンドウを復元",
            ["menu.sharedTaskbar"] = "共有タスクバー（アイコンをクリックするとデスクトップに移動）",
            ["menu.warnUnmanageable"] = "ウィンドウを非表示にできないときに通知",
            ["menu.help"] = "使い方…",
            ["menu.language"] = "言語",
            ["menu.lang.auto"] = "システム（自動）",
            ["menu.startup"] = "Windows 起動時に実行",
            ["menu.update"] = "更新を確認…",
            ["menu.exit"] = "終了",
            ["msg.hotkeyFail"] = "一部のショートカットを登録できませんでした（他のアプリが使用中の可能性）：",
            ["msg.alreadyRunning"] = "IndepenDesk はすでに実行されています。",
            ["msg.startupFail"] = "スタートアップ設定を変更できませんでした。詳細は診断ログを確認してください。",
            ["msg.windowControlFail"] = "ウィンドウを安全に非表示にできなかったため（多くは管理者権限のウィンドウ）、要求されたデスクトップ操作を中止しました。",
            ["msg.sharedTaskbarFail"] = "共有タスクバーモードに切り替えできませんでした（多くは管理者権限のウィンドウ）。以前のモードを維持します。",
            ["msg.windowSkipped"] = "「{0}」({1}) を非表示にできませんでした — おそらく管理者権限のウィンドウです。スキップされ、表示されたままになります。",
            ["update.title"] = "IndepenDesk の更新",
            ["update.available"] = "新しいバージョン {0} が利用可能です（現在: {1}）。\nダウンロードページを開きますか？",
            ["update.none"] = "最新バージョン（{0}）をご利用中です。",
            ["update.error"] = "更新確認のため GitHub に接続できませんでした。しばらくしてから再試行してください。",
            ["update.rateLimited"] = "GitHub が更新確認を一時的に制限しています。しばらくしてから再試行してください。",
            ["update.invalidVersion"] = "リリース版を読み取れませんでした。prcyangli の Releases ページを手動で開いてください。",
            ["osd.desktop"] = "デスクトップ {0}",
            ["ov.title"] = "IndepenDesk — オーバービュー",
            ["ov.legend"] = "⠿  ウィンドウをデスクトップカードへドラッグ   •   カードのタイトルを別のモニター行へドラッグ   •   ウィンドウを右クリック：移動メニュー   •   カードをクリック：切り替え   •   Esc：閉じる",
            ["ov.monitor"] = "モニター {0}",
            ["ov.desktop"] = "⠿ デスクトップ {0}",
            ["ov.active"] = "使用中",
            ["ov.empty"] = "空 — ここにウィンドウをドラッグ",
            ["ov.drop"] = "⬇  ここにドロップ",
            ["ov.menu.move"] = "移動:  モニター {0}  •  デスクトップ {1}",
            ["ov.menu.activeSuffix"] = "（使用中）",
            ["ov.menu.goto"] = "このウィンドウへ移動",
            ["ov.tip.window"] = "デスクトップカードへドラッグ  •  右クリック：移動メニュー",
            ["ov.tip.header"] = "別のモニター行へドラッグするとデスクトップごと移動します",
            ["ov.tip.add"] = "このモニターに新しいデスクトップを作成（切り替えなし）",
            ["ov.tip.closeDesktop"] = "このデスクトップを閉じる",
            ["help.title"] = "IndepenDesk の使い方",
            ["help.shortcuts.header"] = "キーボードショートカット",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   マウスのあるモニターで前 / 次のデスクトップへ（末尾で → は新規作成）\nCtrl+Alt+↑   —   オーバービュー：ウィンドウとデスクトップをドラッグ＆ドロップ\nCtrl+Alt+1..9   —   そのグローバル番号のデスクトップへ移動\nCtrl+Alt+Shift+← / →   —   アクティブウィンドウを隣のデスクトップへ移動",
            ["help.touchpad.header"] = "タッチパッド設定（Windows の既定動作を上書き）",
            ["help.touchpad.body"] = "1.  設定 → Bluetooth とデバイス → タッチパッド → 高度なジェスチャ を開きます。\n2.  4 本指ジェスチャの各方向で「カスタムショートカット」を選んで記録します：\n      左にスワイプ → Ctrl+Alt+←        右にスワイプ → Ctrl+Alt+→        上にスワイプ → Ctrl+Alt+↑\n3.  カスタムショートカットを記録すると Windows の既定動作（全モニター一括切り替え）は\n      自動的に無効になり、      カーソルのあるモニターだけが切り替わります。\n4.  管理者（昇格）ウィンドウにフォーカスがある間、タッチパッドのカスタムショートカットは\n      Windows のセキュリティ（UIPI）により破棄されます。物理キーボードまたはトレイメニューを\n      ご利用ください。",
            ["help.touchpad.open"] = "タッチパッド設定を開く",
            ["help.demo.header"] = "ジェスチャ",
            ["help.demo.swipeLR"] = "4 本指で左右にスワイプ  →  カーソルのあるモニターのデスクトップを切り替え",
            ["help.demo.swipeUp"] = "4 本指で上にスワイプ  →  オーバービュー",
            ["help.close"] = "閉じる",
        },
    };
}
